name: flutter_expense_tracker_project
description: "You have to create an application to capture receipts and purchases for the money that comes in and for the money that goes out. And I should I have two screens that gives details of this entry  In flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
